# Generated by Django 2.0.3 on 2018-03-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180324_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.MoneyType'),
            preserve_default=False,
        ),
    ]
