# Generated by Django 2.0.3 on 2018-03-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180325_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
