# Generated by Django 2.0.3 on 2018-03-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_location_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='passages',
            field=models.ManyToManyField(to='api.Location'),
        ),
    ]
