# Generated by Django 2.0.3 on 2018-03-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180328_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mob',
            old_name='location',
            new_name='locations',
        ),
    ]
