# Generated by Django 2.0.3 on 2018-04-02 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0011_auto_20180328_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('wall_to_wall', 'Стенка на стенку'), ('survival', 'Выживание'), ('open_fight', 'Открытый бой'), ('mob_fight', 'Бой с мобом')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ArenaMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('left', 'Левая'), ('right', 'Правая')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.Arena')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
